### ISSUE TITLE
커뮤니티 검색 시 빠르게 검색하면 계속해서 검색 결과가 추가돼요

### ISSUE THREAD

**Issue by umi0410** [khu-dev/khumu-android#22]
느리게 검색하면 괜찮은데 빠르게 검색하면 검색 결과가 꼬여요.
아무래도 실시간 검색을 하면서 꼬이는 것 같아요.

![Screenshot_20210725-191709](https://user-images.githubusercontent.com/33250725/126895715-1e05cb3f-bdc5-40a3-8438-7ff0017c3f2e.jpg)
![Screenshot_20210725-191719](https://user-images.githubusercontent.com/33250725/126895717-ed73128d-40d7-4af6-9b5a-96509afb59dc.jpg)

- 첫 번째 이미지 - 빠르게 검색했을 때
- 두 번째 이미지 - 느리게 검색했을 때

**Comment by umi0410** [comment]
예를 들어 "A"를 검색하고 빠르게 이어서 "AB"를 검색하게 되는 경우 "A"는 검색 결과가 50개, "AB"는 검색 결과가 0개라고 하자.
이때 A 검색 결과를 처리하는 사이 AB의 검색 결과가 먼저 적용되고 A의 검색 결과가 나중에 적용되어버릴 수 있다.

따라서 실제로 데이터 업데이트 요청을 queuing하는 postValue() 호출 시에 현재 유저가 입력 중인 검색어가 검색 요청 시 입력했던 검색어와 동일한지를 판단함으로써 최대한 동시적 작업으로 인한 오작동을 줄였다.

**Comment by roeniss** [comment]
@umi0410 뒷북이지만, [디바운싱](https://www.zerocho.com/category/JavaScript/post/59a8e9cb15ac0000182794fa) 도 괜찮은 선택지였을 것 같습니다

**Comment by umi0410** [comment]
@roeniss 좋네요 이런 아이디어 ㅎㅎ 나중에 쿼리 너무 많이 날아오면 써볼까봐요. (그런 일이 일어날 정도의 요청이 있을지는 의문이지만..)
